name: Setup
run-name: ${{ github.actor }} Setup
on: [push]
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          chmod +x ./setup.command
          ./setup.command
        shell: bash